### ISSUE TITLE
EnumerateChildren tests don't verify that filtering is actually done

### ISSUE THREAD

**Issue by tylerbutler** [microsoft/wopi-validator-core#10]
The containers.EnumerateChildrenWithOneFilter and containers.EnumerateChildrenWithMultipleFilters tests don't actually verify that the filtering is done by the server. If that can't be done in the validator, it doesn't make much sense to have the tests, since a host who's not implemented filtering at all will still pass those tests.

**Comment by v-stefansi** [comment]
We are in the process of closing this GitHub repository.  This issue has been moved to the CSPP team ADO backlog list for consideration. If you would like to follow up or provide more information, please reach out to csppteam@microsoft.com.
