### ISSUE TITLE
Clarify EnumerateAncesors Documentation

### ISSUE THREAD

**Issue by jgehrig** [microsoft/wopi-validator-core#102]
For the documentation found here:
https://docs.microsoft.com/en-us/microsoft-365/cloud-storage-partner-program/rest/containers/enumerateancestors

This line is vague and has been implemented in different ways by different 3P providers:
> The array must always be ordered such that the ancestor closest to the root is the first element.

Win32 Office depends on the first item in the list being the root folder.

We think the documentation should read as follows:

`The array must always be ordered such that the root container is the first element of the list.`

**Comment by v-stefansi** [comment]
![image](https://user-images.githubusercontent.com/102999875/215228970-710c5919-6c9a-4673-9513-90dac92587d7.png)
