### ISSUE TITLE
Add Validation Case for EnumerateAncestors

### ISSUE THREAD

**Issue by jgehrig** [microsoft/wopi-validator-core#103]
https://docs.microsoft.com/en-us/microsoft-365/cloud-storage-partner-program/rest/containers/enumerateancestors

We should add a test case to the validation tool to ensure that the call to `EnumerateAncestors` for containers behaves consistently across providers.

Currently two providers have implemented the call with different root folder behavior, yet the validation tool passes for both.

We should make sure the tool validates that the root folder is included in the `AncestorsWithRootFirst` list.

Related Issues:
#102 [#178](https://github.com/Microsoft/Office-Online-Test-Tools-and-Documentation/issues/178)

**Comment by skis04** [comment]
Thank you for your suggestion.  We have passed this on to the product team for consideration in a future release.  

We are in the process of closing the WOPI Validator GitHub repository and will no longer be monitoring comments here.  If you have further questions or suggestions, please reach out to the CSPP partner Yammer channel or contact csppteam@microsoft.com.

**Comment by v-stefansi** [comment]
adsfasdfsdafsda
