### ISSUE TITLE
Missing X-Wopi-Proof

### ISSUE THREAD

**Issue by gdevilbat** [microsoft/wopi-validator-core#110]
There is no X-Wopi-Proof on request header.

**Comment by ChangDu2021** [comment]
@gdevilbat I hope you are doing well. May I ask you a question? Do you know how to get the parameter proofKeyProviderNew and proofKeyProviderOld in GetProofKeyHeaders? As my understanding, WOPI request was signed with the private key corresponding to the public key provided in WOPI discovery. And this private key is passed in wopi validator project as parameter. 

//ProofKeyHelper.cs
public static ProofKeyOutput GetSignedProofData(ProofKeyInput proofData, RSACryptoServiceProvider rsaAlg)
{
      ProofKeyOutput output = GetProofData(proofData);

      using (SHA256CryptoServiceProvider hashAlg = new SHA256CryptoServiceProvider())
      {
            byte[] signedProofBytes = rsaAlg.SignData(output.PreSigningBytes, hashAlg);
            output.SignedBase64ProofKey = Convert.ToBase64String(signedProofBytes);

            return output;
      }
}

//WopiRequest.cs
private Dictionary<string, string> GetProofKeyHeaders(string accessToken,
	Uri endpointUri,
	RSACryptoServiceProvider proofKeyProviderNew,
	RSACryptoServiceProvider proofKeyProviderOld,
	long timestamp)
{
	Dictionary<string, string> proofKeyHeaders = new Dictionary<string, string>();

	ProofKeyInput input = new ProofKeyInput(accessToken, timestamp, endpointUri.AbsoluteUri);

	// X-WOPI-Proof
	ProofKeyOutput currentProof = ProofKeysHelper.GetSignedProofData(input, proofKeyProviderNew);
	proofKeyHeaders.Add(Constants.Headers.ProofKey, currentProof.SignedBase64ProofKey);

	// X-WOPI-ProofOld
	ProofKeyOutput oldProof = ProofKeysHelper.GetSignedProofData(input, proofKeyProviderOld);
	proofKeyHeaders.Add(Constants.Headers.ProofKeyOld, oldProof.SignedBase64ProofKey);

	// X-WOPI-TimeStamp
	proofKeyHeaders.Add(Constants.Headers.WopiTimestamp, timestamp.ToString(System.Globalization.CultureInfo.InvariantCulture));

	// save the proof key output to help partners investigate proof key implementation bugs
	this.CurrentProofData = currentProof;
	this.OldProofData = oldProof;

	return proofKeyHeaders;
}

**Comment by ChangDu2021** [comment]
@gdevilbat Is it generated by the follow script? Then ProofWithKey is the private key, Key is the public key. And do you know how to update public key into Discovery.xml?
https://cdn.wictorwilen.se/media/default/Windows-Live-Writer/SharePoint-2013-How-to-extend-WAC-Server_F35A/image_14.png

**Comment by skis04** [comment]
We are in the process of closing WOPI Validator GitHub.  If you still need help with this issue, please reach out to the CSPP partner Yammer channel or contact csppteam@microsoft.com.

**Comment by v-stefansi** [comment]
We are in the process of closing WOPI Validator GitHub. If you still need help with this issue, please reach out to the CSPP partner Yammer channel or contact [csppteam@microsoft.com](mailto:csppteam@microsoft.com).
