### ISSUE TITLE
Add test for hosts that use Transfer-Encoding: chunked for GetFile requests without specifying a SHA256

### ISSUE THREAD

**Issue by tylerbutler** [microsoft/wopi-validator-core#14]
More information: https://github.com/Microsoft/Office-Online-Test-Tools-and-Documentation/issues/242

The host SHOULD provide a hash if they use chunked transfer to prevent a class of bugs where we think we got the whole file but didn't.

**Comment by v-stefansi** [comment]
We are in the process of closing this GitHub repository.  This issue has been moved to the CSPP team ADO backlog list for consideration. If you would like to follow up or provide more information, please reach out to csppteam@microsoft.com.
