### ISSUE TITLE
WopiTimestampOlderThan20Min test can have false positives

### ISSUE THREAD

**Issue by tylerbutler** [Microsoft/wopi-validator-core#18]
The problem is that we sign the requests in the validator using the wall-clock time, not the X-WOPI-Timestamp header we actually send in the request.

This means that when a host gets the request, it is not signed properly, because it was signed with a different Timestamp than the value on the request. So the host correctly returns a 500, but for the *wrong reason*. They should be returning a 500 because the X-WOPI-Timestamp value is older than 20 minutes, but they might *also* return a 500 simply because the proofs don't match due to the timestamp discrepancy.

The fix would be to ensure we're using the timestamp value that we use on the request when actually signing the request. That will ensure that when hosts check the proof, the signature will be correct, and if they still pass the test, it implies they're not checking the timestamp per the spec.

**Comment by MarcinJuraszek** [comment]
I don't have access to that yammer thread, but I'll give it a shot anyway based on the description here.
