### ISSUE TITLE
Add test to check that SHA256, if provided, is correct

### ISSUE THREAD

**Issue by tylerbutler** [microsoft/wopi-validator-core#19]
Ideally this test would check two things:

1. That the SHA256 value was base64-encoded
2. That it matches the hash of the file retrieved via GetFile

**Comment by v-stefansi** [comment]
We are in the process of closing this GitHub repository.  This issue has been moved to the CSPP team ADO backlog list for consideration. If you would like to follow up or provide more information, please reach out to csppteam@microsoft.com.
