### ISSUE TITLE
Determine the fate of the proof key tests

### ISSUE THREAD

**Issue by tylerbutler** [microsoft/wopi-validator-core#22]
The proof key tests can’t work as-is because there’s no signing key. We can disable the tests, but I think a better fix would be to provide a dummy WOPI discovery XML file in this repo and expose a key there. It could be a fixed key since it’s only used for testing.

**Comment by raffis** [comment]
Should be disabled for now, it is irritating that those tests fail even if implemented correctly.

**Comment by thomaslevesque** [comment]
> a better fix would be to provide a dummy WOPI discovery XML file in this repo and expose a key there. It could be a fixed key since it’s only used for testing.

👍 

That's what I did in my working copy to be able to pass those tests. Most of the necessary code is already there, it just needs a key.

**Comment by thomaslevesque** [comment]
I'd like to emphasize how important it is to be able to run these tests locally. We can't use the test WOPI environment to debug on the local machine, so being able to use wopi-validator-core is extremely helpful. There's very little work needed to make the proof key tests work; I can send a PR if you like.

**Comment by tylerbutler** [comment]
PRs are welcome.

**Comment by thomaslevesque** [comment]
@tylerbutler did you see my PR (#86)? I didn't receive any feedback

**Comment by sergiypopovych7576** [comment]
@thomaslevesque @tylerbutler 
Hi guys, is there any progress on this? I see we have a PR, but it was not reviewed 

Also, maybe we can have a small update in Readme to describe how to run proof key tests?

**Comment by mikeebowen** [comment]
@tylerbutler @thomaslevesque , there hasn't been an update on this in quite a while. Are there plans to merge this? Working tests for the proof keys would be very helpful. Thanks!

**Comment by v-stefansi** [comment]
We are in the process of closing this GitHub repository.  This issue has been moved to the CSPP team ADO backlog list for consideration. If you would like to follow up or provide more information, please reach out to csppteam@microsoft.com.

**Comment by mikeebowen** [comment]
@v-stefansi 

Where will this repository be hosted after it has been closed?

**Comment by mikeebowen** [comment]
@v-stefansi ,

The contacts in your post are blocked out. Can you please re-post.

Will this repo be hosted somewhere else publicly, e.g. Azure DevOps, GitLab, etc.?
