### ISSUE TITLE
 Validator WOPI requests should include CorrelationId and UserSessionId headers

### ISSUE THREAD

**Issue by tylerbutler** [microsoft/wopi-validator-core#28]
*Copied from https://github.com/Microsoft/Office-Online-Test-Tools-and-Documentation/issues/359*

This will enable partners to test and verify their request logging/debugging telemetry using the validator. As it is, partners only get those headers when testing with the apps.

**Comment by v-stefansi** [comment]
We are in the process of closing this GitHub repository.  This issue has been moved to the CSPP team ADO backlog list for consideration.
