### ISSUE TITLE
Add test for access_token length

### ISSUE THREAD

**Issue by tylerbutler** [microsoft/wopi-validator-core#3]
As described in https://github.com/Microsoft/Office-Online-Test-Tools-and-Documentation/issues/154, access tokens that are very long can cause problems with Office Online. A good starting length for the validation is 1000 characters I think.

**Comment by v-stefansi** [comment]
We are in the process of closing this GitHub repository.  This issue has been moved to the CSPP team ADO backlog list for consideration. If you would like to follow up or provide more information, please reach out to csppteam@microsoft.com.
