### ISSUE TITLE
Add test to fail if WopiSrc is HTTP instead of HTTPS

### ISSUE THREAD

**Issue by tylerbutler** [microsoft/wopi-validator-core#4]
While HTTP is permitted in the test environment, it is required in production. Having a validator test that fails when HTTP is used will help draw attention to this requirement.

**Comment by v-stefansi** [comment]
We are in the process of closing this GitHub repository.  This issue has been moved to the CSPP team ADO backlog list for consideration. If you would like to follow up or provide more information, please reach out to csppteam@microsoft.com.
