### ISSUE TITLE
Add tests to verify that the WOPI REST endpoint URLs are correct

### ISSUE THREAD

**Issue by tylerbutler** [microsoft/wopi-validator-core#6]
Partners sometimes implement their WOPI endpoints incorrectly, and don't follow the URL schemes defined in the spec. For example, they provide a WopiSrc value like:

https://wopi.contoso.com/wopi/index/fileID/1212121

This will fail to boot the WAC apps because the URL doesn't include /files/. The validator doesn't currently check for this. It should.

**Comment by v-stefansi** [comment]
We are in the process of closing this GitHub repository.  This issue has been moved to the CSPP team ADO backlog list for consideration. If you would like to follow up or provide more information, please reach out to csppteam@microsoft.com.
