### ISSUE TITLE
Proof key debugging info doesn't take overrides into account

### ISSUE THREAD

**Issue by tylerbutler** [microsoft/wopi-validator-core#63]
For example, in the ProofKeys.CurrentValidSignedWithOldKey.OldInvalid test, the X-WOPI-ProofOld header is set to an invalid value, but the debugging info for the ProofOld value does not reflect this.

**Comment by v-stefansi** [comment]
We are in the process of closing this GitHub repository.  This issue has been moved to the CSPP team ADO backlog list for consideration.
