### ISSUE TITLE
Check for response body when none is expected and fail tests

### ISSUE THREAD

**Issue by tylerbutler** [microsoft/wopi-validator-core#7]
An increasing number of implementers are returning JSON responses for operations that don't have a response body defined in WOPI. The validator should verify that responses that should be empty actually are empty.

**Comment by v-stefansi** [comment]
We are in the process of closing this GitHub repository.  This issue has been moved to the CSPP team ADO backlog list for consideration. If you would like to follow up or provide more information, please reach out to csppteam@microsoft.com.
