### ISSUE TITLE
Add test to verify that HostEditUrl and HostViewUrl are not the same

### ISSUE THREAD

**Issue by tylerbutler** [microsoft/wopi-validator-core#71]
These values should be different, because one is expected to open the file in view mode, and the other in edit mode.

This applies to all of the Host*Url properties, actually.

**Comment by v-stefansi** [comment]
We are in the process of closing this GitHub repository.  This issue has been moved to the CSPP team ADO backlog list for consideration.

**Comment by Ashraf111** [comment]
![hosturlerror](https://github.com/microsoft/wopi-validator-core/assets/13987736/d2f6fdfa-08b1-4cc0-b66a-0e5f77745880)
@tylerbutler would you please tell me about this error
