### ISSUE TITLE
Add RenameFile tests that don't require creating new files

### ISSUE THREAD

**Issue by tylerbutler** [microsoft/wopi-validator-core#79]
The RenameFile tests currently require that the host implements either PutRelativeFile or CreateChildFile, because the test creates new files to rename, then deletes them.

We should consider changing the tests or adding new tests so that they don't rely on creating new files. This may have some unwanted side effects, so we should explore more.

**Comment by v-stefansi** [comment]
We are in the process of closing this GitHub repository.  This issue has been moved to the CSPP team ADO backlog list for consideration.
