### ISSUE TITLE
EnumerateAncestors test fails when AncestorsWithRootFirst is empty array

### ISSUE THREAD

**Issue by tylerbutler** [microsoft/wopi-validator-core#8]
An empty array is a valid AncestorsWithRootFirst response for containers, when the EnumerateAncestors call is made on the root container.

**Comment by v-stefansi** [comment]
We are in the process of closing this GitHub repository.  This issue has been moved to the CSPP team ADO backlog list for consideration. If you would like to follow up or provide more information, please reach out to csppteam@microsoft.com.
