### ISSUE TITLE
Stop using zero-byte files when calling PutFile

### ISSUE THREAD

**Issue by tylerbutler** [microsoft/wopi-validator-core#9]
Except in the unlocked 0-byte PutFile case, of course. This causes issues for some hosts. We can address this by making the files we Put as part of the validator > 0 bytes.

**Comment by v-stefansi** [comment]
![image](https://user-images.githubusercontent.com/102999875/215231896-eadfef9f-2134-4a59-9c59-08f3931ddc3b.png)

**Comment by v-stefansi** [comment]
We are in the process of closing this GitHub repository.  This issue has been moved to the CSPP team ADO backlog list for consideration. If you would like to follow up or provide more information, please reach out to csppteam@microsoft.com.

**Comment by v-stefansi** [comment]
We are in the process of closing this GitHub repository.  This issue has been moved to the CSPP team ADO backlog list for consideration. If you would like to follow up or provide more information, please reach out to csppteam@microsoft.com.
