### ISSUE TITLE
Why does validator say missing of X-WOPI-ItemVersion

### ISSUE THREAD

**Issue by ShutaoTang** [microsoft/wopi-validator-core#91]
Recently, I am using `wopi-validator-core` to validate the implementation of wopi protocol. When validator tells me that "the `X-WOPI-ItemVersion` header is not presented on the response" in the first time, I then add this header immdiately. However, the error still exists when I have added that header. Please see the following screenshot.

![微信图片_20200402215759](https://user-images.githubusercontent.com/35004095/78258579-06b9b280-752e-11ea-91a8-fe4dbd9f330e.jpg)

![微信图片_20200402215810](https://user-images.githubusercontent.com/35004095/78258600-0f11ed80-752e-11ea-9dfe-11bcf5de9e2b.jpg)

![微信图片_20200402215815](https://user-images.githubusercontent.com/35004095/78258611-146f3800-752e-11ea-835e-deeec317fbe8.jpg)

**Comment by Prototipo-Erick-Santander** [comment]
I don't know if this helps or if you already solved it, but if your `fileId` is numeric, it needs to be a string, according to the docs.
