### ISSUE TITLE
PutUnlockedFile Fails because it doesn't send empty file

### ISSUE THREAD

**Issue by Prototipo-Erick-Santander** [microsoft/wopi-validator-core#94]
The `PutUnlockedFile` test is failing because the resource "WordBlankDocument", doesn't return a 0 length stream nor does it lock a file first, and, since [the docs](https://wopi.readthedocs.io/projects/wopirest/en/latest/files/PutFile.html#putfile) say 

> "When a host receives a PutFile request on a file that is not locked, the host must check the current size of the file. If it is 0 bytes, the PutFile request should be considered valid and should proceed. If it is any value other than 0 bytes, or is missing altogether, the host should respond with a 409 Conflict. "

I deal with that situation as per the docs and send a `409 Conflict` response when the `stream.Length > 0 && lockValue.IsNullOrEmpty()` but then the test fails.

From what I saw, the only resource that return a 0 length stream is the `"ZeroByteFile.wopitest"`  but the resource being used for this test is "WordBlankDocument", as defined in the TestCases.xml
	
	<TestCase Name="PutUnlockedFile" Category="WopiCore">
	  <Description>
		Simulates creating a new file on the host, which requires PutFile requests to an unlocked 0-byte file to succeed.
	  </Description>
	  <Requests>
		
		<Lock Lock="LockString" />
		<PutFile Lock="LockString" ResourceId="ZeroByteFile" />
		<Unlock Lock="LockString" />

		
		<PutFile ResourceId="WordBlankDocument" />
		<GetFile>
		  <Validators>
			<ResponseContentValidator ExpectedResourceId="WordBlankDocument" />
		  </Validators>
		</GetFile>
	  </Requests>
	  <CleanupRequests>
		
		<Unlock Lock="LockString" />
	  </CleanupRequests>
	</TestCase>

The code of the `Resource.cs` Class

	internal MemoryStream GetContentStream(ILogger logger)
	{
		try
		{
			// Use the filename as the actual content of the stream, unless the FileName is
			// "ZeroByteFile.wopitest". This way we can still write out zero-byte files.
			MemoryStream result = new MemoryStream();
			StreamWriter sw = new StreamWriter(result);
			string fileContent = FileName == "ZeroByteFile.wopitest" ? string.Empty : ResourceId + FilePath + FileName;
			sw.Write(fileContent);
			sw.Flush();
			result.Seek(0, SeekOrigin.Begin);
			return result;
		}
		catch (IOException ex)
		{

			logger.Log("IO Exception when trying to get resource content.");
			logger.Log(ex.Message);
			return null;
		}
	}

Is this a bug of the validator, are the docs wrong? What sould be my course of action here?

Thanks in advance.

**Comment by hafeezsaleh** [comment]
Thanks for sharing. So you can confirm online testing don't have this issue for PutUnlockedFile scenario.

**Comment by jeyasithar** [comment]
I got the same issue and resolved it.
In my case the following was the scenario:
1. WOPI send empty file (basically null body). (My system was originally throwing an exception in this place)
2. I made empty strings write to the file if body is null
3. Compare the existing file to be 0 to validate the test instead of the file being sent as 0 bytes.
4. Issue resolved.

**Comment by v-stefansi** [comment]
We are in the process of closing WOPI Validator GitHub.  If you still need help with this issue, please reach out to the CSPP partner Yammer channel or contact csppteam@microsoft.com.
