### ISSUE TITLE
JsonContentValidator: JsonReaderException thrown while parsing JSON

### ISSUE THREAD

**Issue by Vikcen** [microsoft/wopi-validator-core#96]
Hello.

I'm validating my endpoints running like this:

```
docker run -it --rm tylerbutler/wopi-validator -- -w http://192.168.1.38:8081/wopi/files/80ffd1eb-a6b8-4ec2-adc1-a58b23815eaf -t testToken1 -l 36000000 
```

Ant it is showing the following log in alll the tests:

```
CheckFileInfo, response code: 200 OK
      JsonContentValidator: JsonReaderException thrown while parsing JSON. Are you sure the response is JSON?
```

When i run in my browser that WOPIsrc: http://192.168.1.38:8081/wopi/files/80ffd1eb-a6b8-4ec2-adc1-a58b23815eaf this return in the browser this string:

```
{"OwnerId":"admin","Version":"1.2","Size":"5688","UserId":"admin","BaseFileName":"20200710_1.pdf"}`
```

And that string is a valid  format json.

What could be the problem?

Thank you in advance, and greetings.

**Comment by ndench** [comment]
I'm having this same error. @Vikcen  I realise this is quite an old issue but did you ever find a cause or solution?

**Comment by v-stefansi** [comment]
We are in the process of closing WOPI Validator GitHub.  If you still need help with this issue, please reach out to the CSPP partner Yammer channel or contact csppteam@microsoft.com.
